### ISSUE TITLE
`close()` in `NotificationController` does not return the inner `invokeLifecycle` promise

### ISSUE THREAD

**Issue by otherworld131** [MarcScheib/aurelia-notification#11]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
```

**Current behavior**
The Notification controller `close` returns a Promise which is great. However shouldn't the second `invokeLifecycle` also be returned ? Otherwise the outer promise (created by the first `invokeLifecycle`) will conclude without waiting for the inner promise to complete.

**Expected behavior**
I would expect the inner promise to be returned. That is, instead of having
```          invokeLifecycle(this.viewModel, 'deactivate')```
I would use
```          return invokeLifecycle(this.viewModel, 'deactivate')```

**Minimal reproduction of the problem with instructions**
N/A - it would complex to report it here.

**What is the motivation / use case for changing the behavior?**
This is giving us problems because we have notifications in a modal, which we wish to remove before the modal itself closes. However the `close()`-returned promise ends before the animation is completed and the notification destroyed, hence the notification is still around (although hidden) the next time the modal is opened.

It would be useful to have the `close()` when the notification removal is complete.

**Please tell us about your environment:**
Windows 10, Webpack

* **Version:**
    "aurelia-notify": "^0.7.0",

* **Browser:** Chrome/Electron
 
* **Language:** ES6

* **Node (for AoT issues):** `node --version` = 6.9.1

**Comment by otherworld131** [comment]
Please let me know if you need any other detail!

**Comment by MarcScheib** [comment]
Hi @vitt1984 , 
you are right. I will adjust the `close()` method and have a new version released. I'll update this issue then.

**Comment by MarcScheib** [comment]
Updated the controller in 0.8.1. Thank you for issuing this bug.

**Comment by otherworld131** [comment]
Thanks for responding so quickly!
