### ISSUE TITLE
Fix Typescript Definitions

### ISSUE THREAD

**Issue by fsomme2s** [MarcScheib/aurelia-notification#2]
Hi,

First of all: Great work, thank you! =)

I encountered two problems working in Typescript:
1. I installed aurelia-notify via jspm, but it did not download the "aurelia-notify.d.ts" file. I'm not really deep into jspm, so I'm not sure whether this is a general problem of jspm+github or sth fixable.
2. After i got the definitions manually, the typescript compiler said that my calls to .danger(..), .info(..) etc. were missing a second parameter (settings). Are settings supposed to be obligatory or optional?

**Comment by MarcScheib** [comment]
HI @fsomme2s,

thanks for your comment.

1) I all have to look into this, normally it should work out of the box as I am using the normal build workflow from the aurelia core.

2) This is for sure a bug, I ll update that during the day.

**Comment by MarcScheib** [comment]
Hi @fsomme2s,
both issues should be fixed now.

Again, thanks for your help :)
