### ISSUE TITLE
typings model issue

### ISSUE THREAD

**Issue by AlucardBNS** [MarcScheib/aurelia-notification#5]
Hi,

Basically a small question/request.

Im creating my own view/view-model, but when i want to use the notify method, i realise i can only send a string through. I would like to send my own model through as well.

I added the following overload to the typings : `notify(object: any, settings?: any, level?: string): any;`

but this will break if you make any updates.

Any suggestions?

**Comment by MarcScheib** [comment]
Hi @AlucardBNS 
thanks for your request. You are completely right, at the moment it can only handle a string. I will try to change that by extending it with a model you can hand over to the service.

**Comment by AlucardBNS** [comment]
Oops, should only close an issue one its complete.

Sorry.

**Comment by MarcScheib** [comment]
Hi @AlucardBNS 
I updated the service with your proposed change. It is available in release 0.7.0. I also updated the docs (see https://github.com/MarcScheib/aurelia-notify/blob/master/doc/Intro.md#customization). In fact, your perhaps need to change nothing, except the object you hand over to notify() as the first argument at least needs a property `notification`. Hopefully, you are ok with this?

**Comment by AlucardBNS** [comment]
Hi @MarcScheib 

This is perfect, its already working, 2mins of changes my side.

Thanks so much!
